config/routes.rb
Rails.application.routes.draw do
  resources :sessions do
    resources :instruments
  end
  root 'sessions#index'
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  belongs_to :session
end

app/models/session.rb
class Session < ActiveRecord::Base
  has_many :instruments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def create
    @session = Session.find(params[:session_id])
    @instrument = @session.instruments.create(params[:instrument].permit(:name, :exercise, :tempo, :notes))

    redirect_to session_path(@session)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_session, only: [:show, :edit, :update, :destroy]
  def index
    @sessions = Session.all.order("created_at DESC")
  end

  def show
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(session_params)
    if @session.save
      redirect_to @session
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @session.update(session_params)
      redirect_to @session
    else
      render 'edit'
    end
  end

  def destroy
    @session.destroy
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:date, :session, :mood, :duration)
  end

  def find_session
    @session = Session.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/instruments/_form.html.haml
= simple_form_for([@session, @session.instruments.build]) do |f|
  = f.input :name, input_html: {class: "form-control"}
  = f.input :exercise, input_html: {class: "form-control"}
  = f.input :tempo, input_html: {class: "form-control"}
  = f.input :notes, input_html: {class: "form-control"}
  %br/
  = f.button :submit

app/views/instruments/_instrument.html.haml
%p= instrument.name
%p= instrument.exercise
%p= instrument.tempo
%p= instrument.notes

app/views/layouts/application.html.haml
!!!

%html
%head
  %title Practice Session Tracker
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-header
        = link_to "Practice Tracker", root_path, class: "navbar-brand"
      .nav.navbar-nav.navbar-left
        = link_to "New Session", new_session_path, class: "navbar-link"
.container
  =yield